package wtf.tatp.meowtils.module;

import wtf.tatp.meowtils.gui.ModuleManager;

public final class RegisterModule {
    private RegisterModule() {}
    public static void registerAll() {
        ModuleManager.register(
                new wtf.tatp.meowtils.module.meowtils.GUI(),
                new wtf.tatp.meowtils.module.meowtils.Settings(),
                new wtf.tatp.meowtils.module.meowtils.Notifications(),
                new wtf.tatp.meowtils.module.meowtils.Icons(),
                new wtf.tatp.meowtils.module.meowtils.Teams(),
                new Sprint(), new AutoGG(), new ChatFilter(), new NoParticles(), new NoTitles(),
                new wtf.tatp.meowtils.module.utility.ActionSounds(),
                new wtf.tatp.meowtils.module.utility.AntiObfuscate(),
                new wtf.tatp.meowtils.module.utility.ViewClip(),
                new wtf.tatp.meowtils.module.utility.NullMove(),
                new wtf.tatp.meowtils.module.utility.HotbarLock(),
                new wtf.tatp.meowtils.module.utility.AutoText(),
                new wtf.tatp.meowtils.module.utility.LatencyAlerts(),
                new wtf.tatp.meowtils.module.utility.Freelook(),
                new wtf.tatp.meowtils.module.render.TimeChanger(),
                new wtf.tatp.meowtils.module.render.PingHUD(),
                new wtf.tatp.meowtils.module.render.HealthDisplay(),
                new wtf.tatp.meowtils.module.render.BlockCount(),
                new wtf.tatp.meowtils.module.render.PotionHUD(),
                new wtf.tatp.meowtils.module.render.AntiInvis(),
                new wtf.tatp.meowtils.module.render.Animations(),
                new wtf.tatp.meowtils.module.render.BreakProgress(),
                new wtf.tatp.meowtils.module.render.Cape(),
                new wtf.tatp.meowtils.module.render.ConsumeTimer(),
                new wtf.tatp.meowtils.module.render.InstantHurt(),
                new wtf.tatp.meowtils.module.render.ItemScale(),
                new wtf.tatp.meowtils.module.render.ShinyPots(),
                new wtf.tatp.meowtils.module.render.ChestESP(),
                new wtf.tatp.meowtils.module.render.DamageTags(),
                new wtf.tatp.meowtils.module.render.HealthESP(),
                new wtf.tatp.meowtils.module.render.Indicators(),
                new wtf.tatp.meowtils.module.render.ItemESP(),
                new wtf.tatp.meowtils.module.hypixel.Stats(),
                new wtf.tatp.meowtils.module.hypixel.AutoWho(),
                new wtf.tatp.meowtils.module.hypixel.AutoChannel(),
                new wtf.tatp.meowtils.module.hypixel.Requeue(),
                new wtf.tatp.meowtils.module.hypixel.AutoTip(),
                new wtf.tatp.meowtils.module.hypixel.AccountHider(),
                new wtf.tatp.meowtils.module.hypixel.Denicker(),
                new wtf.tatp.meowtils.module.hypixel.MurdererFinder(),
                new wtf.tatp.meowtils.module.hypixel.NickBot(),
                new wtf.tatp.meowtils.module.hypixel.PartyNotifier(),
                new wtf.tatp.meowtils.module.hypixel.SessionStats(),
                new wtf.tatp.meowtils.module.bedwars.AntiMisplace(),
                new wtf.tatp.meowtils.module.bedwars.ArmorAlerts(),
                new wtf.tatp.meowtils.module.bedwars.BedESP(),
                new wtf.tatp.meowtils.module.bedwars.BedTracker(),
                new wtf.tatp.meowtils.module.bedwars.ConsumeAlerts(),
                new wtf.tatp.meowtils.module.bedwars.EventTimers(),
                new wtf.tatp.meowtils.module.bedwars.HeightOverlay(),
                new wtf.tatp.meowtils.module.bedwars.ItemAlerts(),
                new wtf.tatp.meowtils.module.bedwars.PickupAlerts(),
                new wtf.tatp.meowtils.module.bedwars.ResourceTracker(),
                new wtf.tatp.meowtils.module.bedwars.ShopHelper(),
                new wtf.tatp.meowtils.module.bedwars.TrapNotifier(),
                new wtf.tatp.meowtils.module.bedwars.UpgradeAlerts(),
                new wtf.tatp.meowtils.module.bedwars.UpgradeHUD(),
                new wtf.tatp.meowtils.module.skywars.CooldownHUD(),
                new wtf.tatp.meowtils.module.skywars.EquipAlerts(),
                new wtf.tatp.meowtils.module.skywars.ItemHighlight(),
                new wtf.tatp.meowtils.module.skywars.MiningAlerts(),
                new wtf.tatp.meowtils.module.skywars.NoArmorDye(),
                new wtf.tatp.meowtils.module.skywars.PearlDetector(),
                new wtf.tatp.meowtils.module.skywars.SkywarsAlerts(),
                new wtf.tatp.meowtils.module.skywars.StrengthESP(),
                new wtf.tatp.meowtils.module.antisnipe.AntiCheat(),
                new wtf.tatp.meowtils.module.antisnipe.AutoBlacklist(),
                new wtf.tatp.meowtils.module.antisnipe.AutoSafelist(),
                new wtf.tatp.meowtils.module.antisnipe.PartyDetector(),
                new wtf.tatp.meowtils.module.antisnipe.SniperWarning(),
                new wtf.tatp.meowtils.module.advanced.AutoChest(),
                new wtf.tatp.meowtils.module.advanced.AutoStairs(),
                new wtf.tatp.meowtils.module.advanced.AutoSwap(),
                new wtf.tatp.meowtils.module.advanced.DelayRemover(),
                new wtf.tatp.meowtils.module.advanced.GhostHand());
        OriginalModuleSettings.install();
    }
}
